module.exports = {
    SCROLL_UNDEFINED_ACTION: 'COMMON/SCROLL_UNDEFINED_ACTION',
    CLICK_HELP_MESSAGE_BUTTON: 'COMMON/CLICK_HELP_MESSAGE_BUTTON',
    CHANGE_PAGE: 'COMMON/CHANGE_PAGE',

    DRAFT_NEED_CHECK_PAGE_IMITATION: 'DRAFT_NEED_CHECK_PAGE_IMITATION',
    DRAFT_ADD_PAGE_IMITATION: 'DRAFT_ADD_PAGE_IMITATION',
    DRAFT_REMOVE_PAGE_IMITATION: 'DRAFT_REMOVE_PAGE_IMITATION',

    DRAFT_CHANGE_PAPER_TYPE: 'DRAFT_CHANGE_PAPER_TYPE',
    DRAFT_CHANGE_PAPER_ORIENTATION: 'DRAFT_CHANGE_PAPER_ORIENTATION',

    DRAFT_CHANGE_SCALE: 'DRAFT_CHANGE_SCALE',

    DRAFT_CHANGE_BOTTOM_LINE_PAPER: 'DRAFT_CHANGE_BOTTOM_LINE_PAPER',

    DRAFT_NEED_CHANGE_PAGE_FIELDS: 'DRAFT_NEED_CHANGE_PAGE_FIELDS',
    DRAFT_SET_PAGE_FIELDS_TO_STORE: 'DRAFT_SET_PAGE_FIELDS_TO_STORE',

    DRAFT_DEFINE_SELECTED_TABLE_CELLS: 'DRAFT_DEFINE_SELECTED_TABLE_CELLS',
    DRAFT_NEED_MERGE_TABLE_CELLS: 'DRAFT_NEED_MERGE_TABLE_CELLS',
    DRAFT_NEED_SPLIT_TABLE_CELLS: 'DRAFT_NEED_SPLIT_TABLE_CELLS',
    DRAFT_CONFIG_SPLIT_TABLE_CELLS: 'DRAFT_CONFIG_SPLIT_TABLE_CELLS',
    DRAFT_SELECT_TABLE_ROW: 'DRAFT_SELECT_TABLE_ROW',
    DRAFT_SELECT_TABLE_COLUMN: 'DRAFT_SELECT_TABLE_COLUMN',

    DRAFT_NEED_SHOW_INSERT_ROW_SIGN: 'DRAFT_NEED_SHOW_INSERT_ROW_SIGN',
    DRAFT_NEED_SHOW_INSERT_COLUMN_SIGN: 'DRAFT_NEED_SHOW_INSERT_COLUMN_SIGN',
    DRAFT_DEFINE_CELLS_SHOW_INSERT_COL_SIGN_AFTER: 'DRAFT_DEFINE_CELLS_SHOW_INSERT_COL_SIGN_AFTER',
    DRAFT_DEFINE_CELLS_SHOW_INSERT_ROW_SIGN_AFTER: 'DRAFT_DEFINE_CELLS_SHOW_INSERT_ROW_SIGN_AFTER',
    DRAFT_INSERT_ROW_TABLE: 'DRAFT_INSERT_ROW_TABLE',
    DRAFT_INSERT_COLUMN_TABLE: 'DRAFT_INSERT_COLUMN_TABLE',

    DRAFT_NEED_DELETE_ROWS_WITH_SELECTION: 'DRAFT_NEED_DELETE_ROWS_WITH_SELECTION',
    DRAFT_NEED_DELETE_COLUMNS_WITH_SELECTION: 'DRAFT_NEED_DELETE_COLUMNS_WITH_SELECTION',
    DRAFT_NEED_DELETE_ROWS_WITH_FULL_SELECTION: 'DRAFT_NEED_DELETE_ROWS_WITH_FULL_SELECTION',
    DRAFT_NEED_DELETE_COLUMNS_WITH_FULL_SELECTION: 'DRAFT_NEED_DELETE_COLUMNS_WITH_FULL_SELECTION',


    DRAFT_NEED_SCROLL_TO_CURRENT_CARET_POSITION: 'DRAFT_NEED_SCROLL_TO_CURRENT_CARET_POSITION',

};


