module.exports={
SCROLL_UNDEFINED_ACTION:'COMMON/SCROLL_UNDEFINED_ACTION',
CLICK_HELP_MESSAGE_BUTTON:'COMMON/CLICK_HELP_MESSAGE_BUTTON',
CHANGE_PAGE:'COMMON/CHANGE_PAGE',

DRAFT_NEED_CHECK_PAGE_IMITATION:'DRAFT_NEED_CHECK_PAGE_IMITATION',
DRAFT_ADD_PAGE_IMITATION:'DRAFT_ADD_PAGE_IMITATION',
DRAFT_REMOVE_PAGE_IMITATION:'DRAFT_REMOVE_PAGE_IMITATION',

DRAFT_CHANGE_PAPER_TYPE:'DRAFT_CHANGE_PAPER_TYPE',
DRAFT_CHANGE_PAPER_ORIENTATION:'DRAFT_CHANGE_PAPER_ORIENTATION',

DRAFT_CHANGE_SCALE:'DRAFT_CHANGE_SCALE',

DRAFT_CHANGE_BOTTOM_LINE_PAPER:'DRAFT_CHANGE_BOTTOM_LINE_PAPER',

DRAFT_NEED_CHANGE_PAGE_FIELDS:'DRAFT_NEED_CHANGE_PAGE_FIELDS',
DRAFT_SET_PAGE_FIELDS_TO_STORE:'DRAFT_SET_PAGE_FIELDS_TO_STORE',

DRAFT_NEED_SCROLL_TO_CURRENT_CARET_POSITION:'DRAFT_NEED_SCROLL_TO_CURRENT_CARET_POSITION',

};


