module.exports={
    EXAMPLE_TYPE_ACTION:'EXAMPLE/EXAMPLE',
EXAMPLE_ASYNC_TYPE_ACTION:'EXAMPLE/ASYNC_EXAMPLE',
SCROLL_DOWN_ACTION:'MAINPANEL/SCROLL_DOWN_ACTION',
SCROLL_UP_ACTION:'MAINPANEL/SCROLL_UP_ACTION',
SCROLL_UNDEFINED_ACTION:'MAINPANEL/SCROLL_UNDEFINED_ACTION',
CLICK_HELP_MESSAGE_BUTTON:'MAINPANEL/CLICK_HELP_MESSAGE_BUTTON',

};


