//ВНИМАНИе!!!!!!! СУФФИКСЫ В ХАРДКОДЕ, МЕНЯТЬ ОПАСНО
export const FONT_SIZE_STYLES = {
    FONT_SIZE_5:{
        fontSize:'5px'
    },
    FONT_SIZE_6:{
        fontSize:'6px'
    },
    FONT_SIZE_7:{
        fontSize:'7px'
    },
    FONT_SIZE_8:{
        fontSize:'8px'
    },
    FONT_SIZE_9:{
        fontSize:'9px'
    },
    FONT_SIZE_10:{
        fontSize:'10px'
    },
    FONT_SIZE_11:{
        fontSize:'11px'
    },
    FONT_SIZE_12:{
        fontSize:'12px'
    },
    FONT_SIZE_14:{
        fontSize:'14px'
    },
    FONT_SIZE_16:{
        fontSize:'16px'
    },
    FONT_SIZE_18:{
        fontSize:'18px'
    },
    FONT_SIZE_20:{
        fontSize:'20px'
    },
    FONT_SIZE_24:{
        fontSize:'24px'
    },
    FONT_SIZE_28:{
        fontSize:'28px'
    },
    FONT_SIZE_32:{
        fontSize:'32px'
    },
    FONT_SIZE_36:{
        fontSize:'36px'
    },
    FONT_SIZE_40:{
        fontSize:'40px'
    }
};
