import {UnitOfFontSizePX} from "../../../CommonComps/Service&SAGA/PageSizeConstants";

export let FONT_SIZE_STYLES= FONT_SIZE_STYLES= {
    FONT_SIZE_5:{
        fontSize:`${5*UnitOfFontSizePX}px`
    },
    FONT_SIZE_6:{
        fontSize:`${6*UnitOfFontSizePX}px`
    },
    FONT_SIZE_7:{
        fontSize:`${7*UnitOfFontSizePX}px`
    },
    FONT_SIZE_8:{
        fontSize:`${8*UnitOfFontSizePX}px`
    },
    FONT_SIZE_9:{
        fontSize:`${9*UnitOfFontSizePX}px`
    },
    FONT_SIZE_10:{
        fontSize:`${10*UnitOfFontSizePX}px`
    },
    FONT_SIZE_11:{
        fontSize:`${11*UnitOfFontSizePX}px`
    },
    FONT_SIZE_12:{
        fontSize:`${12*UnitOfFontSizePX}px`
    },
    FONT_SIZE_14:{
        fontSize:`${14*UnitOfFontSizePX}px`
    },
    FONT_SIZE_16:{
        fontSize:`${16*UnitOfFontSizePX}px`
    },
    FONT_SIZE_18:{
        fontSize:`${18*UnitOfFontSizePX}px`
    },
    FONT_SIZE_20:{
        fontSize:`${20*UnitOfFontSizePX}px`
    },
    FONT_SIZE_24:{
        fontSize:`${24*UnitOfFontSizePX}px`
    },
    FONT_SIZE_28:{
        fontSize:`${28*UnitOfFontSizePX}px`
    },
    FONT_SIZE_32:{
        fontSize:`${32*UnitOfFontSizePX}px`
    },
    FONT_SIZE_36:{
        fontSize:`${36*UnitOfFontSizePX}px`
    },
    FONT_SIZE_40:{
        fontSize:`${40*UnitOfFontSizePX}px`
    }
};

