export const FONT_FAMILY_PICKER='FONT_FAMILY_PICKER';
export const COLOR_PICKER='COLOR_PICKER';
export const FONT_SIZE_PICKER='FONT_SIZE_PICKER';
export const COLOR_BG_FILL_PICKER='COLOR_BG_FILL_PICKER';
export const FIELDS_PROPS='FIELDS_PROPS';
export const PAPER_TYPES='PAPER_TYPES';




