export const REGEXP_FONT_FAMILY_SUFFIKS='FONT_FAMILY$';
export const REGEXP_COLOR_SUFFIKS='^COLOR_TEXT';
export const REGEXP_FONT_SIZE_SUFFIKS='^FONT_SIZE_';
export const REGEXP_COLOR_FILL_SUFFIKS='^COLOR_FILL';

